version: "3.8"


services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - /node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
       
    # server:
    #     image: python:3.9-alpine	
    #     command: sh -c "pip install -r requirements.txt && uvicorn main:app --port 8000 --reload --host 0.0.0.0"
    #     ports:
    #         - 8000:8000
    #     working_dir: /server
    #     volumes:
    #         - ./server:/server
            
    # data-server:
    #     image: python:3.9-alpine
    #     command: sh -c "python -m http.server 8001"
    #     ports:
    #         - 8001:8001
    #     working_dir: /data-server
    #     volumes:
    #         - ../EXP2/dataset:/data-server
    
    